jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn package -B --file pom.xml
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Maven
      run: mvn test -B --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - 7
        - 7.0.181
        - 8
        - 8.0.192
        - 9
        - 10
        - 11
        - 11.0.3
        - 12
        - 13
        - 13.0.4
        - 14
        - 15
        - 16
        - 17
        - 18-ea
        os:
        - ubuntu-18.04
        - macOS-latest
        - windows-2016
      max-parallel: 5
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
